import React from 'react'
import { Table, Tr, Th, TdFirst, Td, TdTotal,TdTotalCount } from '../styled'
import styled from 'styled-components'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faEdit } from '@fortawesome/free-solid-svg-icons'

const AddAnalize = () => {
    return (
        <TableAddAnalize>
            <Tr>
                <Th rowSpan="4">Наименование месторождений</Th>
                <Th colSpan="10" style={{position:'relative'}} >Анализ добычи <FontAwesomeIcon style={{position:'absolute', right:'5px', top:'3px', cursor:'pointer'}} icon={faEdit} /> </Th>
            </Tr>
            <Tr>
                <Th colSpan="4">За текущий месяц</Th>
                <Th colSpan="5">С начала года </Th>
            </Tr>
            <Tr>
                <Th rowSpan="2">План добычи тыс.м3</Th>
                <Th rowSpan="2">Факт. добыча тыс.м3 </Th>
                <Th rowSpan="2">% выполнения</Th>
                <Th>Отставание</Th>
                <Th rowSpan="2">План добычи тыс.м3</Th>
                <Th rowSpan="2">Факт. добыча тыс.м3</Th>
                <Th rowSpan="2">За аналог. период прошлого года</Th>
                <Th rowSpan="2">% выполнение </Th>
                <Th>Отставание</Th>
            </Tr>
            <Tr>
                <Th>Перевыполнение</Th>
                <Th>Перевыполнение</Th>
            </Tr>
            <Tr>
                <TdFirst>Шуртан</TdFirst>
                <Td>5000</Td>
                <Td>4500</Td>
                <TdREd>90</TdREd>
                <TdREd>-500</TdREd>
                <Td>60000</Td>
                <Td>59000</Td>
                <Td>70000</Td>
                <TdREd>98</TdREd>
                <TdREd>-1000</TdREd>
            </Tr>
            <Tr>
                <TdFirst>Южная Тандырча</TdFirst>
                <Td>5000</Td>
                <Td>4500</Td>
                <TdREd>90</TdREd>
                <TdREd>-500</TdREd>
                <Td>60000</Td>
                <Td>59000</Td>
                <Td>70000</Td>
                <TdREd>98</TdREd>
                <TdREd>-1000</TdREd>
            </Tr>
            <Tr>
                <TdFirst>Бузахур</TdFirst>
                <Td>5000</Td>
                <Td>4500</Td>
                <TdREd>90</TdREd>
                <TdREd>-500</TdREd>
                <Td>60000</Td>
                <Td>59000</Td>
                <Td>70000</Td>
                <TdREd>98</TdREd>
                <TdREd>-1000</TdREd>
            </Tr>
            <Tr>
                <TdFirst>Восточный Бузахур</TdFirst>
                <Td>5000</Td>
                <Td>4500</Td>
                <TdREd>90</TdREd>
                <TdREd>-500</TdREd>
                <Td>60000</Td>
                <Td>59000</Td>
                <Td>70000</Td>
                <TdREd>98</TdREd>
                <TdREd>-1000</TdREd>
            </Tr>
            <Tr>
                <TdFirst>Тарнасой</TdFirst>
                <Td>5000</Td>
                <Td>4500</Td>
                <TdREd>90</TdREd>
                <TdREd>-500</TdREd>
                <Td>60000</Td>
                <Td>59000</Td>
                <Td>70000</Td>
                <TdREd>98</TdREd>
                <TdREd>-1000</TdREd>
            </Tr>
            <Tr>
                <TdFirst>Ойдин</TdFirst>
                <Td>5000</Td>
                <Td>4500</Td>
                <TdREd>90</TdREd>
                <TdREd>-500</TdREd>
                <Td>60000</Td>
                <Td>59000</Td>
                <Td>70000</Td>
                <TdREd>98</TdREd>
                <TdREd>-1000</TdREd>
            </Tr>
            <Tr>
                <TdFirst>Номозбой</TdFirst>
                <Td>5000</Td>
                <Td>4500</Td>
                <TdREd>90</TdREd>
                <TdREd>-500</TdREd>
                <Td>60000</Td>
                <Td>59000</Td>
                <Td>70000</Td>
                <TdREd>98</TdREd>
                <TdREd>-1000</TdREd>
            </Tr>
            <Tr>
                <TdFirst>Ёрмок</TdFirst>
                <Td>5000</Td>
                <Td>4500</Td>
                <TdREd>90</TdREd>
                <TdREd>-500</TdREd>
                <Td>60000</Td>
                <Td>59000</Td>
                <Td>70000</Td>
                <TdREd>98</TdREd>
                <TdREd>-1000</TdREd>
            </Tr>
            <Tr>
                <TdFirst>Туртсари</TdFirst>
                <Td>5000</Td>
                <Td>4500</Td>
                <TdREd>90</TdREd>
                <TdREd>-500</TdREd>
                <Td>60000</Td>
                <Td>59000</Td>
                <Td>70000</Td>
                <TdREd>98</TdREd>
                <TdREd>-1000</TdREd>
            </Tr>
            <Tr>
                <TdFirst>Северный Шуртан</TdFirst>
                <Td>5000</Td>
                <Td>4500</Td>
                <TdREd>90</TdREd>
                <TdREd>-500</TdREd>
                <Td>60000</Td>
                <Td>59000</Td>
                <Td>70000</Td>
                <TdREd>98</TdREd>
                <TdREd>-1000</TdREd>
            </Tr>
            <Tr>
                <TdFirst>Гармистон</TdFirst>
                <Td>5000</Td>
                <Td>4500</Td>
                <TdREd>90</TdREd>
                <TdREd>-500</TdREd>
                <Td>60000</Td>
                <Td>59000</Td>
                <Td>70000</Td>
                <TdREd>98</TdREd>
                <TdREd>-1000</TdREd>
            </Tr>
            <Tr>
                <TdFirst>Совлигор</TdFirst>
                <Td>5000</Td>
                <Td>4500</Td>
                <TdREd>90</TdREd>
                <TdREd>-500</TdREd>
                <Td>60000</Td>
                <Td>59000</Td>
                <Td>70000</Td>
                <TdREd>98</TdREd>
                <TdREd>-1000</TdREd>
            </Tr>
            <Tr>
                <TdFirst>Яккасарай</TdFirst>
                <Td>5000</Td>
                <Td>4500</Td>
                <TdREd>90</TdREd>
                <TdREd>-500</TdREd>
                <Td>60000</Td>
                <Td>59000</Td>
                <Td>70000</Td>
                <TdREd>98</TdREd>
                <TdREd>-1000</TdREd>
            </Tr>
            <Tr>
                <TdFirst>Мезон</TdFirst>
                <Td>5000</Td>
                <Td>4500</Td>
                <TdREd>90</TdREd>
                <TdREd>-500</TdREd>
                <Td>60000</Td>
                <Td>59000</Td>
                <Td>70000</Td>
                <TdREd>98</TdREd>
                <TdREd>-1000</TdREd>
            </Tr>
            <Tr>
                <TdFirst>Феруза</TdFirst>
                <Td>5000</Td>
                <Td>4500</Td>
                <TdREd>90</TdREd>
                <TdREd>-500</TdREd>
                <Td>60000</Td>
                <Td>59000</Td>
                <Td>70000</Td>
                <TdREd>98</TdREd>
                <TdREd>-1000</TdREd>
            </Tr>
            <Tr>
                <TdFirst>Тошли</TdFirst>
                <Td>5000</Td>
                <Td>4500</Td>
                <TdREd>90</TdREd>
                <TdREd>-500</TdREd>
                <Td>60000</Td>
                <Td>59000</Td>
                <Td>70000</Td>
                <TdREd>98</TdREd>
                <TdREd>-1000</TdREd>
            </Tr>
            <Tr>
                <TdFirst>Зафар</TdFirst>
                <Td>5000</Td>
                <Td>4500</Td>
                <TdREd>90</TdREd>
                <TdREd>-500</TdREd>
                <Td>60000</Td>
                <Td>59000</Td>
                <Td>70000</Td>
                <TdREd>98</TdREd>
                <TdREd>-1000</TdREd>
            </Tr>
            <Tr>
                <TdFirst>Коратепа</TdFirst>
                <Td>5000</Td>
                <Td>4500</Td>
                <TdREd>90</TdREd>
                <TdREd>-500</TdREd>
                <Td>60000</Td>
                <Td>59000</Td>
                <Td>70000</Td>
                <TdREd>98</TdREd>
                <TdREd>-1000</TdREd>
            </Tr>
            <Tr>
                <TdFirst>Ширкент</TdFirst>
                <Td>5000</Td>
                <Td>4500</Td>
                <TdREd>90</TdREd>
                <TdREd>-500</TdREd>
                <Td>60000</Td>
                <Td>59000</Td>
                <Td>70000</Td>
                <TdREd>98</TdREd>
                <TdREd>-1000</TdREd>
            </Tr>
            <Tr>
                <TdFirst>Рубойи</TdFirst>
                <Td>5000</Td>
                <Td>4500</Td>
                <TdREd>90</TdREd>
                <TdREd>-500</TdREd>
                <Td>60000</Td>
                <Td>59000</Td>
                <Td>70000</Td>
                <TdREd>98</TdREd>
                <TdREd>-1000</TdREd>
            </Tr>
            <Tr>
                <TdFirst>Янги Коратепа</TdFirst>
                <Td>5000</Td>
                <Td>4500</Td>
                <TdREd>90</TdREd>
                <TdREd>-500</TdREd>
                <Td>60000</Td>
                <Td>59000</Td>
                <Td>70000</Td>
                <TdREd>98</TdREd>
                <TdREd>-1000</TdREd>
            </Tr>
            <Tr>
                <TdTotal>Итого</TdTotal>
                <TdTotalCount>500</TdTotalCount>
                <TdTotalCount>8000</TdTotalCount>
                <TdTotalCount>9000</TdTotalCount>
                <TdTotalCount>500</TdTotalCount>
                <TdTotalCount>8000</TdTotalCount>
                <TdTotalCount>9000</TdTotalCount>
                <TdTotalCount>500</TdTotalCount>
                <TdTotalCount>8000</TdTotalCount>
                <TdTotalCount>9000</TdTotalCount>
            </Tr>
        </TableAddAnalize>
    )
}

const TableAddAnalize = styled(Table)`
    width:1040px;
    height:125px;
`
const TdREd = styled(Td)`
    color:red;
`
export default AddAnalize
